#!/usr/bin/env python3
"""
Bio Analysis Report for RentMasseur Profiles
Analyzes current bio data across all profiles
"""

import json
from datetime import datetime


def analyze_bios(filepath: str = "data/masseur_profiles.json"):
    """Analyze all bios in the dataset"""
    
    with open(filepath, 'r') as f:
        data = json.load(f)
    
    print("="*80)
    print("RentMasseur Bio Analysis Report")
    print("="*80)
    print(f"Generated: {datetime.now().isoformat()}")
    print(f"Total Profiles: {len(data)}")
    print()
    
    # Count bios
    with_bio = sum(1 for p in data.values() if p.get('bio') and len(p['bio']) > 10)
    without_bio = len(data) - with_bio
    
    print(f"Profiles with bio content: {with_bio}")
    print(f"Profiles without bio content: {without_bio}")
    print()
    
    print("="*80)
    print("DETAILED BIO STATUS")
    print("="*80)
    
    for username, profile in data.items():
        bio = profile.get('bio', '')
        bio_length = len(bio)
        has_content = bio_length > 10
        
        status = "✅ HAS BIO" if has_content else "❌ NO BIO"
        
        print(f"\n{status} - {username}")
        print(f"  URL: {profile['profile_url']}")
        print(f"  Views: {profile.get('total_views', 'N/A')}")
        print(f"  Bio Length: {bio_length} characters")
        
        if has_content:
            print(f"  Bio Preview: {bio[:100]}...")
        else:
            print(f"  Bio: [Empty - blocked by CrowdSec protection]")
    
    print("\n" + "="*80)
    print("SUMMARY")
    print("="*80)
    print(f"Total profiles analyzed: {len(data)}")
    print(f"Bios successfully retrieved: {with_bio} ({with_bio/len(data)*100:.1f}%)")
    print(f"Bios blocked by protection: {without_bio} ({without_bio/len(data)*100:.1f}%)")
    print()
    print("BLOCKING ISSUE:")
    print("RentMasseur.com uses CrowdSec captcha protection on all pages,")
    print("preventing automated extraction of bio content, view counts,")
    print("and registration data from individual profiles.")
    print()
    print("WORKAROUND:")
    print("To get actual bio data, manually visit each profile URL in a browser,")
    print("solve the captcha, and copy the bio text.")
    print()
    print("The only bio currently available is karpathianwolf, which was")
    print("generated by our bio generator script based on view metrics.")


if __name__ == "__main__":
    analyze_bios()
