#!/usr/bin/env python3
"""Point-in-Time Code-Capital Underwriting Scanner.

Measures startup technical substance relative to invested capital at
a financing event. Produces an auditable, point-in-time report with
evidence hashes, eligibility filtering, capital normalization, physical
code measurements, haircuts, and a final underwriting statement.

Usage:
  python3 underwriter.py scan <repo_path> [--capital $3000000] [--date 2026-07-10]
  python3 underwriter.py report <scan_json>
  python3 underwriter.py demo
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

# ─── Frozen Tokenizer Standard ────────────────────────────

TOKENIZER_VERSION = "frozen-v1.0"
TOKENIZER_DELIMITERS = re.compile(
    r'[ \t\n\r\f\v]+|'      # whitespace
    r'(?<=[a-z])(?=[A-Z])|' # camelCase boundaries
    r'(?<=[A-Z])(?=[A-Z][a-z])|' # ABBRWord boundaries
    r'[(){}\[\];,.<>:=+\-*/%&|^~!?@#\'"\\`]'  # operators/punctuation
)

def tokenize_source(source: str) -> List[str]:
    """Frozen tokenizer: deterministic, language-agnostic token splitting."""
    raw = TOKENIZER_DELIMITERS.split(source)
    return [t for t in raw if t]

def count_tokens(source: str) -> int:
    return len(tokenize_source(source))

# ─── Language Detection ───────────────────────────────────

LANGUAGE_MAP = {
    ".py": "python", ".js": "javascript", ".ts": "typescript",
    ".jsx": "javascript", ".tsx": "typescript", ".java": "java",
    ".kt": "kotlin", ".scala": "scala", ".go": "go",
    ".rs": "rust", ".c": "c", ".cpp": "cpp", ".cc": "cpp",
    ".h": "c_header", ".hpp": "cpp_header", ".rb": "ruby",
    ".php": "php", ".swift": "swift", ".m": "objc",
    ".sh": "shell", ".bash": "shell", ".zsh": "shell",
    ".sql": "sql", ".html": "html", ".css": "css",
    ".scss": "scss", ".less": "less", ".vue": "vue",
    ".svelte": "svelte", ".dart": "dart", ".lua": "lua",
    ".r": "r", ".jl": "julia", ".pl": "perl",
    ".tf": "terraform", ".yaml": "yaml", ".yml": "yaml",
    ".json": "json", ".toml": "toml", ".xml": "xml",
    ".md": "markdown", ".rst": "rst", ".txt": "text",
    ".dockerfile": "dockerfile", ".gitignore": "gitignore",
    ".cfg": "config", ".ini": "config", ".conf": "config",
}

FUNCTIONAL_LANGUAGES = {
    "python", "javascript", "typescript", "java", "kotlin", "scala",
    "go", "rust", "c", "cpp", "c_header", "cpp_header", "ruby",
    "php", "swift", "objc", "dart", "lua", "r", "julia", "perl",
    "shell", "sql", "html", "css", "scss", "less", "vue", "svelte",
}

NON_FUNCTIONAL_LANGUAGES = {
    "markdown", "rst", "text", "yaml", "json", "toml", "xml",
    "config", "gitignore", "terraform", "dockerfile",
}

# ─── Exclusion Patterns ───────────────────────────────────

EXCLUDE_DIRS = {
    ".git", "node_modules", "__pycache__", ".venv", "venv",
    "env", ".env", "dist", "build", ".next", ".nuxt",
    "target", "out", "bin", ".cache", ".pytest_cache",
    ".mypy_cache", ".tox", ".eggs", "vendor", "third_party",
    ".idea", ".vscode", "coverage", ".coverage",
    "htmlcov", ".sass-cache", ".gradle", ".mvn",
}

EXCLUDE_PATTERNS = {
    "*.min.js", "*.min.css", "*.map", "*.lock", "*.pyc",
    "*.pyo", "*.class", "*.o", "*.so", "*.dylib", "*.dll",
    "*.exe", "*.wasm", "*.png", "*.jpg", "*.jpeg", "*.gif",
    "*.bmp", "*.ico", "*.svg", "*.pdf", "*.zip", "*.tar",
    "*.gz", "*.bz2", "*.7z", "*.dmg", "*.iso", "*.mp4",
    "*.mp3", "*.wav", "*.avi", "*.mov", "*.db", "*.sqlite",
    "*.sqlite3", "*.log", "*.pid",
}

GENERATED_MARKERS = {
    "auto-generated", "autogenerated", "do not edit",
    "generated by", "code generated", "this file was generated",
    "machine generated", "generated automatically",
}

# ─── File Classification ──────────────────────────────────

@dataclass
class FileMeasurement:
    path: str
    language: str
    is_functional: bool
    is_generated: bool
    is_excluded: bool
    lines_physical: int
    lines_logical: int
    lines_blank: int
    lines_comment: int
    token_count: int
    content_hash: str
    file_size: int
    exclusion_reason: str = ""

    def to_dict(self) -> dict:
        return {
            "path": self.path,
            "language": self.language,
            "is_functional": self.is_functional,
            "is_generated": self.is_generated,
            "is_excluded": self.is_excluded,
            "lines_physical": self.lines_physical,
            "lines_logical": self.lines_logical,
            "lines_blank": self.lines_blank,
            "lines_comment": self.lines_comment,
            "token_count": self.token_count,
            "content_hash": self.content_hash,
            "file_size": self.file_size,
            "exclusion_reason": self.exclusion_reason,
        }

def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()

def detect_generated(content: str, filename: str) -> bool:
    name_lower = filename.lower()
    if name_lower.startswith("generated_") or ".generated." in name_lower:
        return True
    if name_lower.endswith(".min.js") or name_lower.endswith(".min.css"):
        return True
    first_lines = content[:2000].lower()
    for marker in GENERATED_MARKERS:
        if marker in first_lines:
            return True
    return False

def classify_file(path: Path, repo_root: Path) -> FileMeasurement:
    rel = path.relative_to(repo_root).as_posix()
    suffix = path.suffix.lower()
    filename = path.name.lower()

    # Check exclusions
    excluded = False
    reason = ""
    for part in path.parts:
        if part in EXCLUDE_DIRS:
            excluded = True
            reason = f"excluded dir: {part}"
            break
    if not excluded:
        for pattern in EXCLUDE_PATTERNS:
            if path.match(pattern):
                excluded = True
                reason = f"excluded pattern: {pattern}"
                break

    language = LANGUAGE_MAP.get(suffix, "unknown")
    is_functional = language in FUNCTIONAL_LANGUAGES

    if excluded:
        return FileMeasurement(
            path=rel, language=language, is_functional=is_functional,
            is_generated=False, is_excluded=True,
            lines_physical=0, lines_logical=0, lines_blank=0,
            lines_comment=0, token_count=0,
            content_hash="", file_size=0,
            exclusion_reason=reason,
        )

    try:
        content = path.read_text(errors="replace")
    except Exception:
        return FileMeasurement(
            path=rel, language=language, is_functional=is_functional,
            is_generated=False, is_excluded=True,
            lines_physical=0, lines_logical=0, lines_blank=0,
            lines_comment=0, token_count=0,
            content_hash="", file_size=0,
            exclusion_reason="read error",
        )

    is_generated = detect_generated(content, filename)
    if is_generated:
        excluded = True
        reason = "generated code"

    lines = content.splitlines()
    lines_physical = len(lines)
    lines_blank = sum(1 for l in lines if l.strip() == "")
    lines_comment = 0
    in_block_comment = False
    for line in lines:
        stripped = line.strip()
        if in_block_comment:
            lines_comment += 1
            if "*/" in stripped:
                in_block_comment = False
            continue
        if stripped.startswith("#") or stripped.startswith("//"):
            lines_comment += 1
        elif stripped.startswith("/*"):
            lines_comment += 1
            if "*/" not in stripped:
                in_block_comment = True
        elif stripped.startswith('"""') or stripped.startswith("'''"):
            lines_comment += 1
    lines_logical = lines_physical - lines_blank - lines_comment
    if lines_logical < 0:
        lines_logical = 0

    token_count = count_tokens(content) if is_functional else 0
    content_hash = sha256_file(path)
    file_size = path.stat().st_size

    return FileMeasurement(
        path=rel, language=language, is_functional=is_functional,
        is_generated=is_generated, is_excluded=excluded,
        lines_physical=lines_physical, lines_logical=lines_logical,
        lines_blank=lines_blank, lines_comment=lines_comment,
        token_count=token_count, content_hash=content_hash,
        file_size=file_size, exclusion_reason=reason,
    )

# ─── Repository Scanner ───────────────────────────────────

@dataclass
class ScanResult:
    repo_path: str
    scan_timestamp: float
    scan_date: str
    tokenizer_version: str
    protocol_version: str
    files: List[FileMeasurement] = field(default_factory=list)
    total_files: int = 0
    included_files: int = 0
    excluded_files: int = 0
    total_lines_physical: int = 0
    total_lines_logical: int = 0
    total_lines_functional: int = 0
    total_tokens: int = 0
    languages: Dict[str, Dict] = field(default_factory=dict)
    repo_hash: str = ""

    def to_dict(self) -> dict:
        return {
            "repo_path": self.repo_path,
            "scan_timestamp": self.scan_timestamp,
            "scan_date": self.scan_date,
            "tokenizer_version": self.tokenizer_version,
            "protocol_version": self.protocol_version,
            "files": [f.to_dict() for f in self.files],
            "total_files": self.total_files,
            "included_files": self.included_files,
            "excluded_files": self.excluded_files,
            "total_lines_physical": self.total_lines_physical,
            "total_lines_logical": self.total_lines_logical,
            "total_lines_functional": self.total_lines_functional,
            "total_tokens": self.total_tokens,
            "languages": self.languages,
            "repo_hash": self.repo_hash,
        }

def scan_repo(repo_path: str) -> ScanResult:
    """Scan a repository and produce a point-in-time measurement."""
    root = Path(repo_path)
    if not root.exists():
        raise FileNotFoundError(f"repo not found: {repo_path}")

    from datetime import datetime, timezone
    now = datetime.now(timezone.utc)
    result = ScanResult(
        repo_path=str(root.resolve()),
        scan_timestamp=time.time(),
        scan_date=now.strftime("%Y-%m-%d"),
        tokenizer_version=TOKENIZER_VERSION,
        protocol_version="PIUCC-v1.0",
    )

    all_files = sorted(root.rglob("*"))
    file_hashes = []

    for path in all_files:
        if not path.is_file() or path.is_symlink():
            continue
        fm = classify_file(path, root)
        result.files.append(fm)
        result.total_files += 1
        if fm.is_excluded:
            result.excluded_files += 1
        else:
            result.included_files += 1
            result.total_lines_physical += fm.lines_physical
            result.total_lines_logical += fm.lines_logical
            if fm.is_functional:
                result.total_lines_functional += fm.lines_logical
                result.total_tokens += fm.token_count
            file_hashes.append(fm.content_hash)

    # Language breakdown
    lang_stats: Dict[str, dict] = {}
    for fm in result.files:
        if fm.is_excluded:
            continue
        lang = fm.language
        if lang not in lang_stats:
            lang_stats[lang] = {
                "files": 0, "lines_physical": 0, "lines_logical": 0,
                "tokens": 0, "is_functional": fm.is_functional,
            }
        lang_stats[lang]["files"] += 1
        lang_stats[lang]["lines_physical"] += fm.lines_physical
        lang_stats[lang]["lines_logical"] += fm.lines_logical
        if fm.is_functional:
            lang_stats[lang]["tokens"] += fm.token_count
    result.languages = lang_stats

    # Repo hash (Merkle-like over all included file hashes)
    all_hashes = "\n".join(sorted(file_hashes)).encode()
    result.repo_hash = hashlib.sha256(all_hashes).hexdigest()

    return result

# ─── Scoring Engine ───────────────────────────────────────

@dataclass
class UnderwritingResult:
    scan: Dict[str, Any]
    capital_invested: float
    capital_normalized: float
    inflation_adjustment: float
    financing_date: str

    # Physical measurements
    functional_lines: int = 0
    total_tokens: int = 0
    functional_files: int = 0
    language_count: int = 0

    # Haircuts
    generated_haircut: float = 0.0
    test_haircut: float = 0.0
    config_haircut: float = 0.0
    dependency_haircut: float = 0.0
    total_haircut: float = 0.0

    # Adjusted measurements
    adjusted_lines: int = 0
    adjusted_tokens: int = 0

    # Metrics
    capital_per_line: float = 0.0
    capital_per_token: float = 0.0
    tokens_per_dollar: float = 0.0
    lines_per_dollar: float = 0.0

    # Synthetic floor
    synthetic_token_floor: int = 0
    synthetic_line_floor: int = 0

    # Reproduction cost
    reproduction_cost: float = 0.0
    engineering_value_amplification: float = 0.0

    # Complexity (simple proxy)
    avg_file_size: float = 0.0
    max_file_size: int = 0
    file_size_std: float = 0.0

    # Interpretation
    interpretation: str = ""
    risk_flags: List[str] = field(default_factory=list)

    # Final statement
    underwriting_statement: str = ""

    def to_dict(self) -> dict:
        return {k: v for k, v in self.__dict__.items()}

def score_scan(
    scan: ScanResult,
    capital_invested: float = 3_000_000,
    financing_date: str = "",
    inflation_cpi: float = 1.0,
) -> UnderwritingResult:
    """Apply underwriting protocol to a scan result."""
    d = scan.to_dict()

    # Capital normalization
    capital_normalized = capital_invested * inflation_cpi

    result = UnderwritingResult(
        scan=d,
        capital_invested=capital_invested,
        capital_normalized=capital_normalized,
        inflation_adjustment=inflation_cpi,
        financing_date=financing_date or scan.scan_date,
    )

    # Physical measurements
    result.functional_lines = scan.total_lines_functional
    result.total_tokens = scan.total_tokens
    result.functional_files = scan.included_files
    result.language_count = len([l for l in scan.languages if scan.languages[l].get("is_functional")])

    # ─── Haircuts ──────────────────────────────────────
    # Generated code: already excluded during scan, but check for residual
    generated_files = sum(1 for f in scan.files if f.is_generated and not f.is_excluded)
    if result.functional_lines > 0:
        result.generated_haircut = min(generated_files * 100 / result.functional_lines, 0.1)

    # Test code: typically 20-30% of functional code is healthy
    test_files = sum(1 for f in scan.files if not f.is_excluded and
                     ("test" in f.path.lower() or "spec" in f.path.lower()))
    test_lines = sum(f.lines_logical for f in scan.files if not f.is_excluded and
                     ("test" in f.path.lower() or "spec" in f.path.lower()) and f.is_functional)
    if result.functional_lines > 0:
        test_ratio = test_lines / result.functional_lines
        if test_ratio < 0.05:
            result.test_haircut = 0.15  # insufficient tests
            result.risk_flags.append("insufficient test coverage (<5% of functional lines)")
        elif test_ratio < 0.10:
            result.test_haircut = 0.05
            result.risk_flags.append("low test coverage (<10% of functional lines)")

    # Config/infra code: no haircut if reasonable, penalty if excessive
    config_files = sum(1 for f in scan.files if not f.is_excluded and
                       f.language in NON_FUNCTIONAL_LANGUAGES)
    if result.functional_files > 0:
        config_ratio = config_files / max(result.functional_files, 1)
        if config_ratio > 3.0:
            result.config_haircut = 0.10
            result.risk_flags.append(f"excessive config/non-functional ratio ({config_ratio:.1f}x)")

    # Dependency haircut: check for lock files and package manifests
    dep_files = [f for f in scan.files if not f.is_excluded and
                 any(name in f.path for name in
                     ["package.json", "requirements.txt", "Cargo.toml",
                      "go.mod", "pom.xml", "build.gradle", "Gemfile"])]
    if len(dep_files) > 10:
        result.dependency_haircut = 0.05
        result.risk_flags.append(f"high dependency file count ({len(dep_files)})")

    result.total_haircut = (
        result.generated_haircut + result.test_haircut +
        result.config_haircut + result.dependency_haircut
    )
    result.total_haircut = min(result.total_haircut, 0.50)  # cap at 50%

    # Adjusted measurements
    result.adjusted_lines = int(result.functional_lines * (1 - result.total_haircut))
    result.adjusted_tokens = int(result.total_tokens * (1 - result.total_haircut))

    # ─── Capital-to-Code Metrics ───────────────────────
    if result.adjusted_lines > 0:
        result.capital_per_line = capital_normalized / result.adjusted_lines
        result.lines_per_dollar = result.adjusted_lines / capital_normalized
    if result.adjusted_tokens > 0:
        result.capital_per_token = capital_normalized / result.adjusted_tokens
        result.tokens_per_dollar = result.adjusted_tokens / capital_normalized

    # ─── Synthetic Token-Cost Floor ────────────────────
    # Minimum tokens expected for capital invested at industry baseline
    # Assume $100/line average engineering cost, 15 tokens/line average
    result.synthetic_line_floor = int(capital_normalized / 100)
    result.synthetic_token_floor = result.synthetic_line_floor * 15

    # ─── Reproduction Cost Model ───────────────────────
    # Cost to reproduce the codebase at market rates
    avg_rate = 150  # $/hour blended
    avg_lines_per_hour = 25  # industry average for production code
    if result.adjusted_lines > 0:
        result.reproduction_cost = (result.adjusted_lines / avg_lines_per_hour) * avg_rate

    # Engineering value amplification
    if result.reproduction_cost > 0:
        result.engineering_value_amplification = result.reproduction_cost / capital_normalized

    # ─── Complexity Proxy ──────────────────────────────
    included = [f for f in scan.files if not f.is_excluded and f.is_functional]
    if included:
        sizes = [f.lines_logical for f in included]
        result.avg_file_size = sum(sizes) / len(sizes)
        result.max_file_size = max(sizes)
        mean = result.avg_file_size
        result.file_size_std = (sum((s - mean) ** 2 for s in sizes) / len(sizes)) ** 0.5
        if result.max_file_size > 1000:
            result.risk_flags.append(f"very large file detected ({result.max_file_size} logical lines)")
        if result.file_size_std > 200:
            result.risk_flags.append(f"high file size variance (σ={result.file_size_std:.0f})")

    # ─── Interpretation ────────────────────────────────
    if result.adjusted_tokens == 0:
        result.interpretation = "INSUFFICIENT — no functional code detected"
    elif result.capital_per_token > 100:
        result.interpretation = "CAPITAL HEAVY — very little code relative to capital"
    elif result.capital_per_token > 20:
        result.interpretation = "ABOVE MARKET — code substance below expected for capital"
    elif result.capital_per_token > 5:
        result.interpretation = "AT MARKET — code substance consistent with capital"
    elif result.capital_per_token > 1:
        result.interpretation = "EFFICIENT — code substance exceeds capital expectation"
    else:
        result.interpretation = "CODE RICH — substantial code relative to capital"

    # ─── Final Underwriting Statement ──────────────────
    result.underwriting_statement = (
        f"POINT-IN-TIME CODE-CAPITAL UNDERWRITING STATEMENT\n"
        f"{'='*60}\n"
        f"Date: {result.financing_date}\n"
        f"Capital Invested: ${capital_invested:,.2f}\n"
        f"Capital Normalized (CPI={inflation_cpi:.2f}): ${capital_normalized:,.2f}\n"
        f"Repository Hash: {scan.repo_hash[:16]}...\n"
        f"Tokenizer: {TOKENIZER_VERSION}\n"
        f"Protocol: PIUCC-v1.0\n\n"
        f"PHYSICAL MEASUREMENTS\n"
        f"  Functional Lines (logical): {result.functional_lines:,}\n"
        f"  Total Tokens: {result.total_tokens:,}\n"
        f"  Functional Files: {result.functional_files:,}\n"
        f"  Languages: {result.language_count}\n\n"
        f"HAIRCUTS\n"
        f"  Generated Code:    -{result.generated_haircut*100:.1f}%\n"
        f"  Test Coverage:     -{result.test_haircut*100:.1f}%\n"
        f"  Config/Infra:      -{result.config_haircut*100:.1f}%\n"
        f"  Dependencies:      -{result.dependency_haircut*100:.1f}%\n"
        f"  TOTAL HAIRCUT:     -{result.total_haircut*100:.1f}%\n\n"
        f"ADJUSTED MEASUREMENTS\n"
        f"  Adjusted Lines:    {result.adjusted_lines:,}\n"
        f"  Adjusted Tokens:   {result.adjusted_tokens:,}\n\n"
        f"CAPITAL-TO-CODE METRICS\n"
        f"  Capital per Line:  ${result.capital_per_line:,.2f}\n"
        f"  Capital per Token: ${result.capital_per_token:,.4f}\n"
        f"  Tokens per Dollar: {result.tokens_per_dollar:.4f}\n"
        f"  Lines per Dollar:  {result.lines_per_dollar:.6f}\n\n"
        f"SYNTHETIC FLOOR\n"
        f"  Expected Lines:    {result.synthetic_line_floor:,}\n"
        f"  Expected Tokens:   {result.synthetic_token_floor:,}\n"
        f"  Ratio (actual/expected): {result.adjusted_lines/max(result.synthetic_line_floor,1):.2f}x\n\n"
        f"REPRODUCTION COST\n"
        f"  Estimated Cost:    ${result.reproduction_cost:,.2f}\n"
        f"  Value Amplification: {result.engineering_value_amplification:.2f}x\n\n"
        f"INTERPRETATION: {result.interpretation}\n"
    )
    if result.risk_flags:
        result.underwriting_statement += f"\nRISK FLAGS:\n"
        for flag in result.risk_flags:
            result.underwriting_statement += f"  ⚠ {flag}\n"
    result.underwriting_statement += f"\n{'='*60}\n"

    return result

# ─── CLI ──────────────────────────────────────────────────

def cmd_scan(args):
    scan = scan_repo(args.repo_path)
    output_path = args.output or f"scan_{Path(args.repo_path).name}_{scan.scan_date}.json"
    with open(output_path, "w") as f:
        json.dump(scan.to_dict(), f, indent=2)
    print(f"Scan complete: {output_path}")
    print(f"  Files: {scan.total_files} total, {scan.included_files} included, {scan.excluded_files} excluded")
    print(f"  Functional lines: {scan.total_lines_functional:,}")
    print(f"  Total tokens: {scan.total_tokens:,}")
    print(f"  Repo hash: {scan.repo_hash[:16]}...")
    print(f"  Tokenizer: {TOKENIZER_VERSION}")

def cmd_report(args):
    with open(args.scan_json) as f:
        scan_dict = json.load(f)
    scan = ScanResult(
        repo_path=scan_dict["repo_path"],
        scan_timestamp=scan_dict["scan_timestamp"],
        scan_date=scan_dict["scan_date"],
        tokenizer_version=scan_dict["tokenizer_version"],
        protocol_version=scan_dict["protocol_version"],
        files=[FileMeasurement(**fm) for fm in scan_dict["files"]],
        total_files=scan_dict["total_files"],
        included_files=scan_dict["included_files"],
        excluded_files=scan_dict["excluded_files"],
        total_lines_physical=scan_dict["total_lines_physical"],
        total_lines_logical=scan_dict["total_lines_logical"],
        total_lines_functional=scan_dict["total_lines_functional"],
        total_tokens=scan_dict["total_tokens"],
        languages=scan_dict["languages"],
        repo_hash=scan_dict["repo_hash"],
    )
    result = score_scan(scan, capital_invested=args.capital, financing_date=scan.scan_date)
    print(result.underwriting_statement)
    if args.output:
        with open(args.output, "w") as f:
            json.dump(result.to_dict(), f, indent=2)
        print(f"Full report saved: {args.output}")

def cmd_demo(args):
    """Run the underwriter on the HDAR codebase itself."""
    repo = os.path.dirname(os.path.abspath(__file__))
    print(f"Scanning: {repo}")
    scan = scan_repo(repo)
    result = score_scan(scan, capital_invested=3_000_000, financing_date=scan.scan_date)
    print(result.underwriting_statement)

def main():
    ap = argparse.ArgumentParser(description="Point-in-Time Code-Capital Underwriting Scanner")
    sub = ap.add_subparsers(dest="command")

    p_scan = sub.add_parser("scan", help="Scan a repository")
    p_scan.add_argument("repo_path")
    p_scan.add_argument("--output", "-o", default="")

    p_report = sub.add_parser("report", help="Generate underwriting report from scan")
    p_report.add_argument("scan_json")
    p_report.add_argument("--capital", type=float, default=3_000_000)
    p_report.add_argument("--output", "-o", default="")

    sub.add_parser("demo", help="Run on this codebase")

    args = ap.parse_args()
    if args.command == "scan":
        cmd_scan(args)
    elif args.command == "report":
        cmd_report(args)
    elif args.command == "demo":
        cmd_demo(args)
    else:
        ap.print_help()

if __name__ == "__main__":
    main()
