#!/usr/bin/env python3
"""
RentMasseur Bio Strategy 18: yoga_fusion
Generated by strategy generator.
"""

import sys
import json
from rentmasseur_core import (
    setup_driver, login, update_bio, groq_generate_bio, save_bio_field,
)

STRATEGY_NAME = "yoga_fusion"
STRATEGY_PROMPT = """Yoga + massage fusion. Stretching, flexibility, mind-body connection. Flow, balance, zen. CTA."""
HEADLESS = True


def main():
    driver = setup_driver(headless=HEADLESS)
    try:
        if not login(driver):
            print(json.dumps({"login": False, "bio": False}))
            sys.exit(1)

        result = update_bio(driver, "")
        if result is None or (isinstance(result, dict) and result.get("error")):
            print(json.dumps({"login": True, "bio": False, "error": "bio_field_not_found"}))
            sys.exit(1)

        field_info, current_bio = result
        new_bio = groq_generate_bio(STRATEGY_NAME, STRATEGY_PROMPT, current_bio)
        if not new_bio:
            print(json.dumps({"login": True, "bio": False, "error": "generation_failed"}))
            sys.exit(1)

        saved = save_bio_field(driver, field_info, new_bio)
        print(json.dumps({"login": True, "bio": saved, "strategy": STRATEGY_NAME}))
        sys.exit(0 if saved else 1)
    finally:
        driver.quit()


if __name__ == "__main__":
    main()
